add_newline = true
# palette = "catppuccin_mocha"
palette = "rose-pine-dawn"
command_timeout = 1000

[character]
success_symbol = "[❯](bold foam)"
error_symbol = "[❯](bold love)"
vimcmd_symbol = "[❮](bold gold)"

[directory]
truncation_length = 4
style = "bold overlay"

[line_break]
disabled = false

[username]
style_user = "bold iris"
style_root = "bold rose"
show_always = true
format = "[$user]($style) in "

[hostname]
ssh_only = true
format = "on [$hostname](bold gold) "

[os.symbols]
Windows = "🤖 "
Ubuntu = "🐧 "

[os]
format = "[$symbol]($style)"
disabled = false


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'
